// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PRN232.GradingEngine.Infrastructure.Persistence;

#nullable disable

namespace PRN232.GradingEngine.Infrastructure.Migrations
{
    [DbContext(typeof(GradingDbContext))]
    [Migration("20260702211910_UpdateTestSectionResults")]
    partial class UpdateTestSectionResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PRN232.Domain.Entities.ExamRubric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DeductionPointsPerNamingError")
                        .HasColumnType("numeric");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForbidHardcodedConnectionString")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("numeric");

                    b.Property<string>("SolutionPattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExamRubrics");
                });

            modelBuilder.Entity("PRN232.Domain.Entities.RequiredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamRubricId")
                        .HasColumnType("uuid");

                    b.Property<bool>("MustExist")
                        .HasColumnType("boolean");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamRubricId");

                    b.ToTable("RequiredFiles");
                });

            modelBuilder.Entity("PRN232.Domain.Entities.RequiredProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExamRubricId")
                        .HasColumnType("uuid");

                    b.Property<bool>("MustExist")
                        .HasColumnType("boolean");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExamRubricId");

                    b.ToTable("RequiredProjects");
                });

            modelBuilder.Entity("PRN232.Domain.Entities.SubmissionAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Band0Passed")
                        .HasColumnType("boolean");

                    b.Property<bool>("Band1Passed")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("BuildErrors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("NamingViolations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("ScoreDeductions")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestSectionResults")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("PRN232.Domain.Entities.RequiredFile", b =>
                {
                    b.HasOne("PRN232.Domain.Entities.ExamRubric", "ExamRubric")
                        .WithMany("RequiredFiles")
                        .HasForeignKey("ExamRubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamRubric");
                });

            modelBuilder.Entity("PRN232.Domain.Entities.RequiredProject", b =>
                {
                    b.HasOne("PRN232.Domain.Entities.ExamRubric", "ExamRubric")
                        .WithMany("RequiredProjects")
                        .HasForeignKey("ExamRubricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamRubric");
                });

            modelBuilder.Entity("PRN232.Domain.Entities.ExamRubric", b =>
                {
                    b.Navigation("RequiredFiles");

                    b.Navigation("RequiredProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
